version: "3.8"

networks:
    dev:
        driver: bridge

services:
    php81-service:
        restart: unless-stopped
        image: lucasluk798/php:8.1
        container_name: php81-container
        volumes:
            - .:/var/www:delegated
        environment:
            APP_ENV: dev

    #MYSQL
    mysql8-service:
        image: mysql:8.0
        container_name: mysql8-container
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony-vuejs-api-crud
        volumes:
            - ./var:/var/www/var
            - ./tools/docker/mysql:/var/lib/mysql

    #ADMINER
    adminer-service:
        image: adminer
        container_name: adminer-container
        ports:
            - "8080:8080"
        environment:
            APP_ENV: dev
            ADMINER_DEFAULT_SERVER: mysql8-service
            ADMINER_DESIGN: pepa-linha

    #NGINX
    nginx-service:
        image: nginx:stable-alpine
        restart: unless-stopped
        container_name: nginx-container
        volumes:
            - .:/var/www:delegated
            - ./tools/docker/web/config.conf:/etc/nginx/conf.d/default.conf
            - ./tools/docker/web/log/:/var/log/nginx/
        env_file:
            - .env
        environment:
            NGINX_HOST: sf6api
            NGINX_PORT: 80
        ports:
            - "8000:80"
        depends_on:
            - php81-service
            - mysql8-service

    #MAILHOG
    mailhog-service:
        image: mailhog/mailhog
        container_name: mailhog-container
        logging:
            driver: "none"
        ports:
            - "8025:8025"
            - "1025:1025"
