version: "3.8"

networks:
    dev:
        driver: bridge

services:
    php81-service:
        restart: unless-stopped
        image: lucasluk798/php:8.1
        container_name: php81-container
        volumes:
            - .:/var/www:delegated
        environment:
            - APP_ENV:dev

    #NGINX
    nginx-service:
        image: nginx:stable-alpine
        restart: unless-stopped
        container_name: nginx-container
        ports:
            - "8000:80"
        volumes:
            - .:/var/www:delegated
            - ./tools/docker/web/config.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php81-service
            - mysql8-service
        links:
            - php81-service

    #MYSQL
    mysql8-service:
        image: mysql:8.0
        container_name: mysql8-container
        ports:
            - "4306:3306"
        command: --default-authentication-plugin=mysql_native_password --character-set=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: s6_api_crud_docker
        volumes:
            - ./var:/var/www/var:rw
            - ./tools/docker/mysql:/var/lib/mysql
    #ADMINER
    adminer-service:
        image: adminer
        container_name: adminer-container
        ports:
            - "8080:8080"
        environment:
            APP_ENV: dev
            ADMINER_DEFAULT_SERVER: mysql8-service
            ADMINER_DESIGN: pepa-linha

    #MAILHOG
    mailhog-service:
        image: mailhog/mailhog
        container_name: mailhog-container
        logging:
            driver: "none"
        ports:
            - "8025:8025"
            - "1025:1025"
